name: Update PR Description

on:
  pull_request:
    branches:
      - dev
      
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        body-template: |
          ## Checklists
          ### Checklist (author)
          - [ ] The CHANGELOG description is clear to reviewers & PAs
          - [ ] Documentation is checked (existing updated, newly written, or not necessary)
          - [ ] Related PRs are linked
          - [ ] I have filled in this template
