name: Update PR Description

on:
  pull_request:
    branches:
      - main
      
jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
    - uses: riskledger/update-pr-description@dev
      with:
        body: |
          "This is just random check you need to pass before"
        token: ${{ secrets.GITHUB_TOKEN }}
